POST http:/localhost:8000/api/hotels 
Content-Type: application/json
{
    "name":"asdf",
    "type":"hotel",
    "city":"asdf",
    "address":"asdf",
    "distance":"asdf",
    "title":"asdf",
    "desc":"asdf",
    "cheapestPrice":122,
  
}


