POST  http://localhost:8000/api/hotels
Content-Type: application/json

{
    "name":"Bibek",
    "type":"hotel",
    "city":"asdf",
    "address":"asdf",
    "distance":"asdf",
    "title":"asdf",
    "desc":"asdf",
    "cheapestPrice":122
  
}

POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{ 
    "username":"Bibek",
    "email":"hotel",
    "password":"asdf"
}


POST  http://localhost:8000/api/auth/login
Content-Type: application/json

{ 
    "username":"Bibek",
    "email":"hotel",
    "password":"asdf"
}

